import { useMemo, useState } from 'react'
import { Eye, EyeOff, Pin, PinOff, Search, X } from 'lucide-react'
import { api } from '../api'
import type { Channel, Shill } from '../types'
import { ago, cap, fx, longAgo, ratio, shortAddress } from '../utils/format'
import { Avatar, ChainIcon, ChannelAvatar } from './TokenIdentity'
import './ChannelsPage.css'

export function ChannelsPage({ channels, shills, ignored, refresh, onOpenShill }: { channels: Channel[], shills: Shill[], ignored: boolean, refresh: () => void, onOpenShill: (shill: Shill) => void }) {
    // Channel search is local and immediate because the complete channel list is
    // already loaded; no extra backend request is needed for every keystroke.
    const [channelSearch, setChannelSearch] = useState('')
    const [showHidden, setShowHidden] = useState(false)
    // Hidden ignored channels remain persisted and searchable on demand; the
    // toggle only changes presentation and never resumes Telegram monitoring.
    const visibleChannels = useMemo(() => channels.filter(channel => channel.is_ignored === ignored && (!ignored || showHidden || !channel.is_hidden) && channel.name.toLowerCase().includes(channelSearch.trim().toLowerCase())), [channels, ignored, showHidden, channelSearch])
    const hiddenCount = channels.filter(channel => channel.is_ignored && channel.is_hidden).length
    const pinned = visibleChannels.filter(channel => channel.is_pinned), all = visibleChannels.filter(channel => !channel.is_pinned)
    const lastShill = (channel: Channel) => channel.last_shill_at ? `Last shill: ${longAgo(channel.last_shill_at)} (${new Date(channel.last_shill_at).toLocaleDateString([], { day: '2-digit', month: 'short', year: 'numeric' })})` : 'Last shill: never'
    // Pinned and regular monitored channels are separate, non-duplicated groups;
    // ignored channels retain one list and emphasize their most recent activity.
    // A shill row is a navigation shortcut into the canonical All Tokens detail
    // view, preserving one modal implementation instead of duplicating details.
    const renderChannel = (c: Channel) => { const channelShills = shills.filter(shill => shill.channel_id === c.telegram_id); return <article className="channel-column" key={c.telegram_id}><header><ChannelAvatar channelId={c.telegram_id} name={c.name} photo={c.has_photo} size={56} /><div><b>{c.name}</b><small>{c.shill_count} shills · Median {fx(c.median_current_x)}</small>{ignored && <small className="last-shill">{lastShill(c)}</small>}</div><span className="channel-actions">{!ignored && <button className={`pin-channel ${c.is_pinned ? 'active' : ''}`} title={c.is_pinned ? 'Unpin channel' : 'Pin channel'} onClick={async () => { await api.setPinned(c.telegram_id, !c.is_pinned); refresh() }}>{c.is_pinned ? <PinOff /> : <Pin />}{c.is_pinned ? 'Unpin' : 'Pin'}</button>}{ignored && <button className="hide-channel" onClick={async () => { await api.setHidden(c.telegram_id, !c.is_hidden); refresh() }}>{c.is_hidden ? <Eye /> : <EyeOff />}{c.is_hidden ? 'Show channel' : 'Hide channel'}</button>}<button onClick={async () => { await api.setIgnored(c.telegram_id, !c.is_ignored); refresh() }}>{c.is_ignored ? 'Start monitoring' : 'Ignore channel'}</button></span></header><section className="channel-shills">{channelShills.map(shill => { const current = ratio(shill.current_market_cap, shill.initial_market_cap); return <div className="channel-shill" role="button" tabIndex={0} key={shill.id} onClick={() => onOpenShill(shill)} onKeyDown={event => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); onOpenShill(shill) } }}><Avatar shill={shill} size={40} /><div><b>{shill.symbol ?? shortAddress(shill.contract_address)}</b><small><ChainIcon chain={shill.chain_id} />{ago(shill.shilled_at)}</small></div><dl><span><dt>Initial</dt><dd>{cap(shill.initial_market_cap)}</dd></span><span><dt>Current</dt><dd>{cap(shill.current_market_cap)}</dd></span><span><dt>X</dt><dd className={(current ?? 0) >= 1 ? 'gain' : 'loss'}>{fx(current)}</dd></span></dl></div> })}{!channelShills.length && <div className="no-channel-shills">No shills recorded yet</div>}</section></article> }
    const section = (title: string, items: Channel[]) => <section className="channel-section"><h2>{title}<b>{items.length}</b></h2>{items.length ? <div className="channel-grid channel-columns">{items.map(renderChannel)}</div> : <div className="channel-section-empty">{title === 'Pinned Channels' ? 'Pin important channels to keep them here.' : 'No matching channels in this section.'}</div>}</section>
    return <main className="page channels-page"><div className="title channel-title"><div><h1>{ignored ? 'Ignored Channels' : 'Channels'}</h1><p>{ignored ? 'Telegram messages from these channels are skipped. Hidden only controls this list.' : 'Monitored Telegram channels and their shill history.'}</p></div><div className="channel-title-actions">{ignored && <button className={`hidden-toggle ${showHidden ? 'active' : ''}`} onClick={() => setShowHidden(value => !value)}>{showHidden ? <EyeOff /> : <Eye />}{showHidden ? 'Hide hidden channels' : `Show hidden channels (${hiddenCount})`}</button>}<label className="search channel-search"><Search /><input value={channelSearch} onChange={event => setChannelSearch(event.target.value)} placeholder={`Search ${ignored ? 'ignored channels' : 'channels'}…`} />{channelSearch && <button aria-label="Clear search" onClick={() => setChannelSearch('')}><X /></button>}</label></div></div><div className="channel-count">Showing <b>{visibleChannels.length}</b> of {channels.filter(channel => channel.is_ignored === ignored).length}</div>{ignored ? section(showHidden ? 'Ignored Channels · including hidden' : 'Ignored Channels', visibleChannels) : <>{section('Pinned Channels', pinned)}{section('All Channels', all)}</>}{!visibleChannels.length && <div className="empty channel-empty"><Search /><b>No matching channels</b><span>{ignored && hiddenCount && !showHidden ? 'Use “Show hidden channels” to include hidden results.' : 'Try a different channel name.'}</span></div>}</main>
}
