import { useState } from 'react'
import { Check, Copy, ExternalLink, RefreshCw, Trash2 } from 'lucide-react'
import type { HistoryPoint, Shill } from '../types'
import { ago, cap, fx, ratio, shortAddress } from '../utils/format'
import { Avatar, ChainLabel, ChannelAvatar, CopyActionButton, TokenSocials } from './TokenIdentity'
import { MarketChart } from './MarketChart'
import './TokenDetail.css'

export function Detail({ shill, history, pollSeconds, onRemove, onRetry }: { shill: Shill, history: HistoryPoint[], pollSeconds: number, onRemove: () => void, onRetry: () => void }) {
    const [confirm, setConfirm] = useState(false), [contractCopied, setContractCopied] = useState(false), current = ratio(shill.current_market_cap, shill.initial_market_cap), max = ratio(shill.max_market_cap, shill.initial_market_cap)
    const dex = shill.chain_id && shill.pair_address ? `https://dexscreener.com/${shill.chain_id}/${shill.pair_address}` : `https://dexscreener.com/search?q=${encodeURIComponent(shill.contract_address)}`
    const padre = shill.chain_id ? `https://trade.padre.gg/trade/${shill.chain_id}/${shill.contract_address}` : null
    // Contract identity belongs in the hero beside the symbol; the metadata row
    // can then balance source channel against the resolved project name.
    // Current X represents profit only from 1x upward; applying the same threshold
    // used by cards and tables makes sub-1x drawdowns red in the detail hero.
    // A dedicated backdrop keeps destructive confirmation above the sticky
    // action footer; nesting the old popover in the detail stacking context let
    // the full-width Remove button paint over its text and controls.
    return <section className="detail"><header className="detail-hero"><Avatar shill={shill} size={62} /><div className="detail-identity"><div className="detail-title-line"><h2>{shill.symbol ?? 'Unresolved token'}</h2><button className={`hero-contract ${contractCopied ? 'copied' : ''}`} title="Copy contract address" onClick={async () => { await navigator.clipboard.writeText(shill.contract_address); setContractCopied(true); window.setTimeout(() => setContractCopied(false), 1600) }}><span>{shortAddress(shill.contract_address)}</span>{contractCopied ? <Check /> : <Copy />}</button></div><ChainLabel chain={shill.chain_id} /></div><div className="hero-token-name"><small>Token name</small><b>{shill.token_name ?? 'Name unavailable'}</b></div><TokenSocials shill={shill} /><div className="big-x"><b className={(current ?? 0) >= 1 ? 'gain' : 'loss'}>{fx(current)}</b><small>Current X</small></div></header><div className="metrics"><Metric label="Initial MC" value={cap(shill.initial_market_cap)} /><Metric label="Current MC" value={cap(shill.current_market_cap)} /><Metric label="Max X" value={fx(max)} positive /><Metric label="Time shilled" value={ago(shill.shilled_at)} /></div>{shill.market_status === 'unavailable' && <div className="warning"><div><b>Initial market cap unavailable</b><span>DEX Screener may have current data while historical candles are unavailable. Retry to resolve it now.</span></div><button onClick={onRetry}><RefreshCw />Retry</button></div>}<div className="detail-content"><div><div className="meta"><span><small>Channel</small><b><ChannelAvatar channelId={shill.channel_id} name={shill.channel_name} photo={shill.channel_has_photo} size={24} />{shill.channel_name}</b></span></div><div className="message"><small>Original message</small><b><ChannelAvatar channelId={shill.channel_id} name={shill.channel_name} photo={shill.channel_has_photo} size={34} />{shill.channel_name}</b><p>{shill.message}</p></div></div><MarketChart points={history} pollSeconds={pollSeconds} shilledAt={shill.shilled_at} /></div><footer className="detail-actions"><a href={dex} target="_blank">Open DEX chart<ExternalLink /></a>{padre && <a href={padre} target="_blank">Open Terminal chart<ExternalLink /></a>}<CopyActionButton value={shill.contract_address} /><button className="remove" onClick={() => setConfirm(true)}>Remove token<Trash2 /></button></footer>{confirm && <div className="confirm-backdrop" onMouseDown={() => setConfirm(false)}><div className="confirm-dialog" role="alertdialog" aria-modal="true" aria-labelledby="remove-token-title" onMouseDown={event => event.stopPropagation()}><b id="remove-token-title">Permanently remove {shill.symbol ?? 'this token'}?</b><span>This deletes the token, its shills, tracking periods, and every market-cap sample. This cannot be undone.</span><div className="confirm-actions"><button onClick={() => setConfirm(false)}>Cancel</button><button className="danger" onClick={onRemove}>Remove permanently</button></div></div></div>}</section>
}
export function Metric({ label, value, positive }: { label: string, value: string, positive?: boolean }) { return <div className="metric"><small>{label}</small><b className={positive ? 'gain' : ''}>{value}</b></div> }

